[workspace]
members = [
  "common",
  "api",
  # "cli",
  # "integration-tests"
]

[workspace.package]
edition = "2021"
version = "0.5.0"
authors = ["Mahdi <Mahdi.robatipoor@gmail.com>"]
description = "transfer file command line tool"
homepage = "https://github.com/robatipoor/pf"
readme = "./README.md"
keywords = ["paste", "file","transfer"]
repository = "https://github.com/robatipoor/pf"
documentation = ""
license = "MIT"

[profile.release]
strip = true
opt-level = "z"
lto = true

[workspace.dependencies]
tokio = { version = "1.27.0",features = ["macros","time","process","net","rt-multi-thread"] }
axum = { version = "0.6.14",features = ["headers","multipart"]}
axum-extra = { version = "0.7.3",features = ["async-read-body"]}
hyper = "0.14.25"
config = { version = "0.13.3",default-features = false, features = ["toml"] }
chrono = { version = "0.4.24", features = ["serde"] }
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.60"
anyhow = "1.0.70"
thiserror = "1.0.40"
reqwest = { version = "0.11.16", default-features = false,features = ["json","multipart","stream","rustls-tls"] }
fake = { version = "2.5.0", features = ['derive', 'uuid', 'chrono'] }
rand = "0.8.5"
regex = "1.7.2"
cuid2 = "0.1.0"
qrcodegen = "1.8.0"
futures-util = "0.3.27"
strum = "0.24.1"
strum_macros = "0.24.3"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
url = "2.3.1"
once_cell = { version = "1.17.1" }
validator = { version = "0.16.0", features = ["derive"] }
async-trait = "0.1.68"
test-context = "0.1.4"
build_html = "2.4.0"
tokio-util = "0.7.7"
project-root = "0.2.2"
