[workspace]
members = [
  "sdk",
  "api",
  # "app",
  "cli",
  # "integration-tests"
  "example"
]

[workspace.package]
edition = "2021"
version = "0.5.0"
authors = ["Mahdi <Mahdi.robatipoor@gmail.com>"]
description = "transfer file"
homepage = "https://github.com/robatipoor/pf"
readme = "./README.md"
keywords = ["paste", "file","transfer"]
repository = "https://github.com/robatipoor/pf"
documentation = ""
license = "MIT"

[profile.release]
strip = true
opt-level = "z"
lto = true

[workspace.dependencies]
tokio = { version = "1.28.1",features = ["macros","time","process","net","rt-multi-thread"] }
axum = { version = "0.6.18",features = ["headers","multipart"]}
axum-extra = { version = "0.7.4",features = ["async-read-body"]}
sled = "0.34.7"
tower-http = {version = "0.4.0" ,features = ["fs"]}
tower = {version = "0.4.13",features = ["util"]}
hyper = "0.14.26"
config = { version = "0.13.3",default-features = false,features = ["toml"] }
chrono = { version = "0.4.24",features = ["serde"] }
serde = { version = "1.0.163",features = ["derive"] }
serde_json = "1.0.96"
bincode = "1.3.3"
anyhow = "1.0.71"
thiserror = "1.0.40"
reqwest = { version = "0.11.17",default-features = false,features = ["json","multipart","stream","rustls-tls"] }
multer = "2.1.0"
fake = { version = "2.6.1",features = ['derive', 'uuid', 'chrono'] }
rand = "0.8.5"
httpmock = { version = "0.6.0"}
regex = "1.8.1"
cuid2 = "0.1.0"
qrcodegen = "1.8.0"
futures-util = "0.3.28"
strum = "0.24.1"
strum_macros = "0.24.3"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
url = "2.3.1"
mime_guess = "2.0.4"
clap = {version = "4.2.7",features = ["derive"]}
once_cell = { version = "1.17.1" }
validator = { version = "0.16.0",features = ["derive"] }
async-trait = "0.1.68"
test-context = "0.1.4"
build_html = "2.4.0"
tokio-util = "0.7.8"
argon2 = "0.5.0"
base64 = "0.21.0"
project-root = "0.2.2"
log-derive = "0.4.1"
log = "0.4.17"
assert_cmd = "2.0.11"
