[workspace]
members = [
  "sdk",
  "api",
  "cli", # "app",  # "integration-tests"
]

[workspace.package]
authors = ["Mahdi <Mahdi.robatipoor@gmail.com>"]
description = "transfer file"
documentation = ""
edition = "2021"
homepage = "https://github.com/robatipoor/pf"
keywords = ["paste", "file", "transfer"]
license = "MIT"
readme = "./README.md"
repository = "https://github.com/robatipoor/pf"
version = "0.5.0"

[profile.release]
lto = true
opt-level = "z"
strip = true

[workspace.dependencies]
anyhow = "1.0.71"
argon2 = "0.5.0"
assert_cmd = "2.0.11"
async-stream = {version = "0.3.5"}
async-trait = "0.1.71"
axum = {version = "0.6.18", features = ["headers", "multipart"]}
axum-extra = {version = "0.7.4", features = ["async-read-body"]}
base64 = "0.21.2"
bincode = "1.3.3"
build_html = "2.4.0"
chrono = {version = "0.4.26", features = ["serde"]}
clap = {version = "4.3.11", features = ["derive"]}
config = {version = "0.13.3", default-features = false, features = ["toml"]}
cuid2 = "0.1.0"
fake = {version = "2.6.1", features = ['derive', 'uuid', 'chrono']}
futures-util = "0.3.28"
wiremock = {version = "0.5"}
hyper = "0.14.27"
indicatif = "0.17.5"
log = "0.4.19"
log-derive = "0.4.1"
mime_guess = "2.0.4"
multer = "2.1.0"
once_cell = {version = "1.18.0"}
project-root = "0.2.2"
qrcodegen = "1.8.0"
rand = "0.8.5"
regex = "1.9.1"
reqwest = {version = "0.11.18", default-features = false, features = ["json", "multipart", "stream", "rustls-tls"]}
serde = {version = "1.0.169", features = ["derive"]}
serde_json = "1.0.100"
sled = "0.34.7"
strum = "0.25.0"
strum_macros = "0.25.1"
test-context = "0.1.4"
thiserror = "1.0.43"
tokio = {version = "1.29.1", features = ["macros", "time", "process", "net", "rt-multi-thread"]}
tokio-util = "0.7.8"
tower = {version = "0.4.13", features = ["util"]}
tower-http = {version = "0.4.1", features = ["fs"]}
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
url = "2.4.0"
validator = {version = "0.16.1", features = ["derive"]}
