[package]
name = "cli"
version = "0.1.0"
edition.workspace = true

[dependencies]
sdk = { path = "../sdk" }
clap = { workspace = true }
tokio = { workspace = true }
chrono = { workspace = true }
config = { workspace = true }
anyhow = { workspace = true }
futures-util = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strum_macros = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
mime_guess = { workspace = true }
validator = { workspace = true }
thiserror = { workspace = true }
fake = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }
once_cell = { workspace = true }
reqwest = { workspace = true }
httpmock = { workspace = true }
assert_cmd = { workspace = true }
async-trait = { workspace = true }
test-context = { workspace = true }
