# Maximum upload size in bytes
max_upload_bytes_size = 1000_000_000 # 1GB
# Default code length in the url
default_code_length = 3
# Default expiration time in seconds
default_expire_secs = 7200

[server]
# Communication protocol (e.g., "http" or "https")
schema = "http"
# Host IP address for the server
host = "127.0.0.1"
# Port number for the server
port = 8080
# TLS key file path
file_tls_key_path = "key.pem"
# TLS certificate file path
file_tls_cert_path = "cert.pem"

[fs]
# Base directory for file system operations
base_dir = "tmp/fs"

[db]
# Path directory to the database file
path_dir = "tmp/db"
