name: test coverage

on:
  push:
    branches: ["coverage-test-problem"]

jobs:
  test:
    name: coverage
    runs-on: ubuntu-latest
    env:
      APP_PROFILE: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Cache tarpaulin
        uses: actions/cache@v4
        id: cache-tarpaulin
        with:
          path: |
            ~/.cargo/bin/cargo-tarpaulin
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Install tarpaulin
        if: ${{ steps.cache-tarpaulin.outputs.cache-hit != 'true' }}
        continue-on-error: true
        run: |
          cargo install cargo-tarpaulin --git https://github.com/xd009642/tarpaulin --branch fix/missing-coverage-functions

      - name: Generate code coverage
        run: |
          cargo +nightly tarpaulin --verbose --all-features --workspace --timeout 120 --engine llvm --out Xml

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          fail_ci_if_error: true
